// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: chat.sql

package db

import (
	"context"
)

const getChatThread = `-- name: GetChatThread :one
SELECT id, thread_id, user_address, thread_name, created_at, updated_at, is_deleted FROM chat_threads
WHERE thread_id = $1
AND user_address = $2
AND is_deleted = FALSE
`

type GetChatThreadParams struct {
	ThreadID    string `json:"threadId"`
	UserAddress string `json:"userAddress"`
}

func (q *Queries) GetChatThread(ctx context.Context, arg GetChatThreadParams) (ChatThread, error) {
	row := q.db.QueryRow(ctx, getChatThread, arg.ThreadID, arg.UserAddress)
	var i ChatThread
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.UserAddress,
		&i.ThreadName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getChatThreads = `-- name: GetChatThreads :many
SELECT thread_id, thread_name FROM chat_threads
WHERE user_address = $1
AND is_deleted = FALSE
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetChatThreadsParams struct {
	UserAddress string `json:"userAddress"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

type GetChatThreadsRow struct {
	ThreadID   string `json:"threadId"`
	ThreadName string `json:"threadName"`
}

func (q *Queries) GetChatThreads(ctx context.Context, arg GetChatThreadsParams) ([]GetChatThreadsRow, error) {
	rows, err := q.db.Query(ctx, getChatThreads, arg.UserAddress, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChatThreadsRow{}
	for rows.Next() {
		var i GetChatThreadsRow
		if err := rows.Scan(&i.ThreadID, &i.ThreadName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChatThread = `-- name: InsertChatThread :one
INSERT INTO chat_threads (thread_id, user_address, thread_name)
VALUES ($1, $2, $3)
RETURNING id, thread_id, user_address, thread_name, created_at, updated_at, is_deleted
`

type InsertChatThreadParams struct {
	ThreadID    string `json:"threadId"`
	UserAddress string `json:"userAddress"`
	ThreadName  string `json:"threadName"`
}

func (q *Queries) InsertChatThread(ctx context.Context, arg InsertChatThreadParams) (ChatThread, error) {
	row := q.db.QueryRow(ctx, insertChatThread, arg.ThreadID, arg.UserAddress, arg.ThreadName)
	var i ChatThread
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.UserAddress,
		&i.ThreadName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}
