// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Pool struct {
	ID        string             `json:"id"`
	Token0ID  string             `json:"token0_id"`
	Token1ID  string             `json:"token1_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Price struct {
	ID        int64              `json:"id"`
	PoolID    string             `json:"pool_id"`
	PriceUsd  pgtype.Numeric     `json:"price_usd"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Token struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Symbol    string             `json:"symbol"`
	Decimals  int32              `json:"decimals"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
