// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreatePool(ctx context.Context, arg CreatePoolParams) (Pool, error)
	CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error)
	GetPool(ctx context.Context, id string) (Pool, error)
	GetPools(ctx context.Context) ([]Pool, error)
}

var _ Querier = (*Queries)(nil)
