services:
  db:
    image: postgres:latest
    restart: unless-stopped
    container_name: yexus-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - yexus_db:/var/lib/postgresql/data
    networks:
      - yexus-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    restart: unless-stopped
    container_name: yexus-openobserve
    environment:
      ZO_ROOT_USER_EMAIL: ${ZO_ROOT_USER_EMAIL}
      ZO_ROOT_USER_PASSWORD: ${ZO_ROOT_USER_PASSWORD}
      ZO_HTTP_AUTH_BASIC_USER: ${ZO_ROOT_USER_EMAIL}
      ZO_HTTP_AUTH_BASIC_PASSWORD: ${ZO_ROOT_USER_PASSWORD}
    ports:
      - "5080:5080"
    volumes:
      - yexus_openobserve_data:/data
    networks:
      - yexus-network
  api:
    image: yexus-api
    container_name: yexus-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 12345:12345
    volumes:
      - ./.env:/app/.env
    depends_on:
      yexus_db:
        condition: service_healthy
      openobserve:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:12345/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - yexus-network
    init: true

volumes:
  yexus_db:
  yexus_openobserve_data:

networks:
  yexus-network:
    driver: bridge