services:
  db:
    image: postgres:latest
    restart: unless-stopped
    container_name: yexus_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - yexus_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    restart: unless-stopped
    container_name: yexus-openobserve
    environment:
      ZO_ROOT_USER_EMAIL: ${ZO_ROOT_USER_EMAIL}
      ZO_ROOT_USER_PASSWORD: ${ZO_ROOT_USER_PASSWORD}
      ZO_HTTP_AUTH_BASIC_USER: ${ZO_ROOT_USER_EMAIL}
      ZO_HTTP_AUTH_BASIC_PASSWORD: ${ZO_ROOT_USER_PASSWORD}
    ports:
      - "5080:5080"
    volumes:
      - yexus_openobserve_data:/data

volumes:
  yexus_db:
  yexus_openobserve_data:

