CREATE TYPE ORDER_STATUS AS ENUM ('PENDING', 'PARTIAL_FILLED' ,'FILLED', 'REJECTED', 'CANCELLED');
CREATE TYPE ORDER_SIDE AS ENUM ('BUY', 'SELL');
CREATE TYPE ORDER_TYPE AS ENUM ('MARKET', 'LIMIT', 'STOP', 'TWAP');

CREATE TABLE IF NOT EXISTS orders (
    id BIGSERIAL PRIMARY KEY,
    pool_id VARCHAR(42) NOT NULL,
    parent_id BIGINT,
    wallet VARCHAR(42),
    status ORDER_STATUS NOT NULL DEFAULT 'PENDING',
    side ORDER_SIDE NOT NULL,
    type ORDER_TYPE NOT NULL,
    price NUMERIC(78,18) NOT NULL,
    amount NUMERIC(78,18) NOT NULL,
    twap_amount NUMERIC(78,18),
    twap_parts INT,
    partial_filled_at TIMESTAMP WITH TIME ZONE,
    filled_at TIMESTAMP WITH TIME ZONE,
    cancelled_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE,

    FOREIGN KEY (pool_id) REFERENCES pools(id) ON DELETE CASCADE,
    FOREIGN KEY (parent_id) REFERENCES orders(id) ON DELETE CASCADE
);
